-- 01.
-- What is the total revenue generated by each product category in the e-commerce database?
-- The query calculates revenue, cost, and profit by joining order_items, products, and orders.

SELECT p.category AS product_category, 
       ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent / 100)), 2) AS total_revenue,
       ROUND(SUM(p.cost * oi.quantity), 2) AS total_cost,
       ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent / 100) - p.cost * oi.quantity), 2) AS total_profit
FROM products p 
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY p.category
ORDER BY total_revenue DESC;

-- 02.
-- What is the top-selling product in each category?

SELECT 
       category,
       product_name,
       quantity_sold
FROM (SELECT 
       p.product_name AS product_name, 
       p.category AS category, 
       SUM(oi.quantity) AS quantity_sold,
       ROW_NUMBER() OVER (PARTITION BY p.category ORDER BY SUM(oi.quantity) DESC) AS category_rank
FROM products AS p
JOIN order_items AS oi
ON p.product_id = oi.product_id
GROUP BY p.product_id) ranked_products
WHERE category_rank = 1
ORDER BY quantity_sold DESC

-- What is the month-over-month sales growth
WITH monthly_sales AS (
       SELECT 
              strftime('%Y', order_date) AS year,
              strftime('%m', order_date) AS month,
              SUM(total_amount) AS total_sales
       FROM orders
       WHERE status = 'Completed'
       GROUP BY strftime('%Y', order_date), strftime('%m', order_date)
       ORDER BY year, month),
monthly_with_lag AS(
       SELECT 
              year,
              month,
              total_sales,
              LAG(total_sales) OVER (ORDER BY year, month) AS prev_mo_sales,
              round((total_sales - LAG(total_sales) OVER (ORDER BY year, month)) / LAG(total_sales) OVER (ORDER BY year, month) * 100, 2) AS mo_over_mo_sales_growth
       FROM monthly_sales)
SELECT *
FROM monthly_with_lag 
WHERE prev_mo_sales IS NOT NULL
ORDER BY year, month

-- What is the month-over-month sales growth by category
WITH monthly_sales AS (
       SELECT 
              strftime('%Y', o.order_date) AS year,
              strftime('%m', o.order_date) AS month,
              p.category AS category,
              SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent / 100)) AS total_sales       
       FROM orders AS o
       JOIN order_items AS oi
              ON o.order_id = oi.order_id
       JOIN products AS p
              ON oi.product_id = p.product_id
       WHERE o.status = 'Completed'
       GROUP BY strftime('%Y', o.order_date), strftime('%m', o.order_date), p.category
       ),
monthly_with_lag AS(
       SELECT 
              year,
              month,
              category,
              total_sales,
              LAG(total_sales) OVER (PARTITION BY category ORDER BY year, month) AS prev_mo_sales,
              round((total_sales - LAG(total_sales) OVER (PARTITION BY category ORDER BY year, month)) / LAG(total_sales) OVER (PARTITION BY category ORDER BY year, month) * 100, 2) AS mo_over_mo_sales_growth
       FROM monthly_sales)
SELECT *
FROM monthly_with_lag 
WHERE prev_mo_sales IS NOT NULL
ORDER BY year, month, category

-- 4. Which customers spent the most in the last 90 days?
-- identifies 90 day date range
with date_range AS(
       SELECT 
              MAX(order_date) AS max_date,
              DATE(MAX(order_date), '-90 days') AS start_date
       FROM orders
),
-- groups the customer spend over the date range
customer_spend AS(
SELECT 
       o.customer_id AS customer_id,
       c.first_name || ' ' || c.last_name AS customer_name,
       SUM(o.total_amount) AS total_spent
FROM orders AS o
JOIN customers AS c
       ON o.customer_id = c.customer_id
CROSS JOIN date_range AS d
WHERE o.status = 'Completed'
       AND o.order_date >= d.start_date
GROUP BY o.customer_id
),
-- ranks the customers
ranked_customers AS(
       SELECT
              ROW_NUMBER() OVER (ORDER BY total_spent DESC) AS rank,
              customer_id,
              customer_name,
              total_spent
       FROM customer_spend
)
-- final query
SELECT *
FROM ranked_customers
LIMIT 20
